<h2 style="border:1px solid white;background-color:#66AD47;text-align:center;padding:10px;border-radius:5px">What is Tensor?</h2>

<p style='color:#5A20CB'>A tensor is usually a multi-dimensional array (exactly like a numpy ndarray), but it can also hold a scalar (a simple value such as 42).</p>

<h2 style="border:1px solid white;background-color:#66AD47;text-align:center;padding:10px;border-radius:5px">Tensors and Operations</h2>

In [1]:
import tensorflow as tf

In [2]:
## you can create a tensor with tf.constant()

new_tensor = tf.constant([[1. , 2. , 3.], [4. , 5. , 6.]])
new_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [4]:
## tf.Tensor has shape and data type

print('shape:')
new_tensor.shape

shape:


TensorShape([2, 3])

In [5]:
new_tensor.dtype

tf.float32

In [6]:
## indexing in tensorflow works much like numpy

new_tensor[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [7]:
## all sort of operations are available with tensors

new_tensor + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [8]:
tf.square(new_tensor)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [9]:
new_tensor @ tf.transpose(new_tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

<p style='color:#5A20CB'>other basic functions include:</p>

<p style='color:#5A20CB'>tf.add(), tf.mulitply(), tf.exp(), tf.sqrt(), tf.reshape(), tf.squeeze(), tf.tile(), tf.reduce_mean(), tf.reduce_sum(),
tf.reduce_max(), tf.math.log(), etc.</p>

<h2 style="border:1px solid white;background-color:#66AD47;text-align:center;padding:10px;border-radius:5px">Tensors and NumPy</h2>

<p style='color:#5A20CB'>Tensors play nice with numpy: you can create a tensor from a numpy array, and vice versa. You can even apply tensorflow operations to numpy arrays and numpy operations to tensors</p>

In [10]:
import numpy as np

t = tf.constant([[1. , 2. , 3.], [4. , 5. , 6.]])
n = np.array([10. , 12. , 14.])

In [11]:
tf.constant(n,tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 12., 14.], dtype=float32)>

In [12]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [13]:
tf.square(n)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([100., 144., 196.])>

In [14]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

<p style='color:#5A20CB'>Notice that numpy uses 64-bit precision by default, while tensorflow uses 32-bit. This is because 32-bit precision is generally more than enough for neural networks, plus it runs faster and uses less RAM. So when you create a tensor from a numpy array, make sure to set dtype=tf.float32.</p>

<h2 style="border:1px solid white;background-color:#66AD47;text-align:center;padding:10px;border-radius:5px">Type Conversion</h2>

<p style='color:#5A20CB'>Tyep conversions can significantly hurt performance, and they can easily go unnoticed when they are done automatically. To avoid this, Tensorflow does not perform any type conversions automatically: it just raises an exception if you try to execute an operation on tensors with incompatible types. For example, you cannot add a float tensor to an integer tensor, and you cannot even add a 32-bit float and a 64-bit float.</p>

In [15]:
tf.constant(3.) + tf.constant(23)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

<p style='color:#5A20CB'>You can use tf.cast() when you really need to convert types.</p>

In [16]:
t1 = tf.constant(20.0, tf.float32)
t2 = tf.constant(12)
t1 + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=32.0>

<h2 style="border:1px solid white;background-color:#66AD47;text-align:center;padding:10px;border-radius:5px">Variables</h2>

<p style='color:#5A20CB'>the tf.Tensor values we've seen so far are immutable: you cannot modify them. This means that we cannot use regular tensors to implement weights in a neural network, since they need to be tweaked by backpropagation. Plus, other parameters may also need to change over time. What we need is tf.Variable.</p>

In [17]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

<p style='color:#5A20CB'>A tf.Variable acts much like a tf.Tensor: you can perform the same operations with it, it plays nicely with NumPy as well, and it is just as pickly with types. But it can also be modified in place using the assign() method. You can also modify individual cells (or slices), by using the cell's (or slices's) assign() method or by using scatter_update() or scatter_nd_update() methods.</p>

In [18]:
v.assign(v * 2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [19]:
v[0,1].assign(100.0)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  2., 100.,   6.],
       [  8.,  10.,  12.]], dtype=float32)>

In [20]:
v[:,1].assign([42., 43.])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 43., 12.]], dtype=float32)>

<h2 style="border:1px solid white;background-color:#66AD47;text-align:center;padding:10px;border-radius:5px">Other Data Structures</h2>

<p style='color:#5A20CB'>Tensorflow supports several other data structures, including the following:</p>
<p style='color:#5A20CB'><strong>Sparse Tensor (tf.SparseTensor)</strong>: Efficiently represent tensors containing mostly zeros. The tf.sparse package contains operations for sparse tensors.</p>
<p style='color:#5A20CB'><strong>Tensor Arrays (tf.TensorArray)</strong>: Are lists of tensors. They have a fixed size by default but can optionally be made dynamic. All tensors they contain must have the same shape and data type.</p>
<p style='color:#5A20CB'><strong>Ragged Tensor (tf.RaggedTensor)</strong>: Represent static lists of lists of tensors, where every tensor has the same shape an data type. The tf.ragged package contains operations for ragged tensors.</p>
<p style='color:#5A20CB'><strong>String Tensors</strong>: Are regular tensors of type tf.string. These represent byte strings, not Unicode strings, so if you create a string tensor using Unicode string (e.g., a regular python 3 string liek "cafe"), then it will get encoded to UTF-8 automatically. Alternatively, you can represent Unicode strings using tensors of type tf.int32, where each item represents a Unicode code point (e.g., [99, 97, 102, 233]). The string package contains operations for byte strings and Unicode strings (and to convert one to other). It's important to note that a tf.string is atomic, meaning that its length does not appear in the tensor's shape. Once you convert it to a Unicode tensor (i.e., a tensor of type tf.int32 holding Unicode code points), the length appears in the shape.</p>
<p style='color:#5A20CB'>Some other data structures: <strong>sets, queues</strong></p>